Lecture 3 Calendar
js-tasks-ru/htmlcss-20220919_mokruschin-vadim pull request #11
Opened 2022-10-03 12:24 UTC by v-mokrushin

Сделал календарь

2022-10-03 12:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 18:42 UTC, GSemikozov requested changes

2022-10-03 18:42 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__external-selected-item {
calendar__date-item_external-selected

2022-10-03 18:42 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__inner-selected-item {
calendar__date-item_inner-selected

2022-10-03 19:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-03 19:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-03 19:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-04 05:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-04 05:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-04 05:15 UTC, v-mokrushin commented
Подлил master

2022-10-05 05:53 UTC, GSemikozov approved these changes

2022-10-05 05:54 UTC, merged