Lecture 4 Layout
js-tasks-ru/htmlcss-20220919_mokruschin-vadim pull request #14
Opened 2022-10-05 12:48 UTC by v-mokrushin

Доделал header
Попробовал адаптивность

2022-10-05 12:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-06 05:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-06 06:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-06 08:17 UTC, GSemikozov requested changes

2022-10-06 08:17 UTC, GSemikozov commented on components/card/card.css
> +.card__tooltip {
мод каждый встраиваемый компонент не надо создавать элемент - так мы не напасемся классов + каждый раз надо будет не только встаивать блок, но и не забывать добавить нужный класс в другой компонент (Карточка). Лучше просто общие паддинги в превью, и выравнивать по середине. Остальные модификации размеров - на уровне самих блоков

2022-10-06 08:17 UTC, GSemikozov commented on components/histogram/histogram.css
> +        height: 76px;
все-таки будет лишним ограничением

2022-10-06 08:34 UTC, v-mokrushin commented on components/histogram/histogram.css
> +        height: 76px;
ахах, извиняюсь, оно уже 3-ий раз выплывает, я не могу понять откуда... я его убираю, в следующем коммите оно опять здесь

2022-10-06 09:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-06 09:58 UTC, v-mokrushin commented
Переделал карточки:
-задал общий padding у PC версии
-добавил wrapper для центровки контента карточки
- в мобильной версии padding задаётся по-другому, всё работает

2022-10-06 20:01 UTC, GSemikozov approved these changes

2022-10-06 20:01 UTC, merged