Task 3 layout
js-tasks-ru/htmlcss-20220919_mokruschin-vadim pull request #5
Opened 2022-09-25 10:56 UTC by v-mokrushin

Вёрстка странички

2022-09-25 10:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-26 08:36 UTC, GSemikozov requested changes

2022-09-26 08:36 UTC, GSemikozov commented on assets/css/main.css
> +    max-width: 1200px;
все-таки 1110

2022-09-26 10:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 04:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 12:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-27 12:09 UTC, v-mokrushin commented
Поправил конфликты

2022-09-29 07:52 UTC, GSemikozov approved these changes

2022-09-29 07:52 UTC, merged